name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Checking Code style
        run: sbt check
      
      - name: Build and Publish to Local
        run: sbt +publishLocal        

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
        redis-version: [ 4 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Run Test
        run: sbt coverage test coverageReport

      - name: Aggregate coverage report
        run: sbt coverageAggregate

      - name: Upload test coverage report
        run: bash <(curl -s https://codecov.io/bash)

  ci:
    runs-on: ubuntu-20.04
    needs: [ build, test ]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"